modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/sekwah41/Naruto-Mod/issues"
license="MIT"
[[mods]]
    modId="sekclib"
    version="${file.jarVersion}"
    displayName="SekC Lib"
    updateJSONURL="https://www.sekwah.com/modversions/sekclib.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/sekclib"
    authors="Sekwah41"
    description='''
A library mod designed to make aspects of modding easier, in particular network syncing with clients.

Other features and utilities are also included.
'''

[[dependencies.sekclib]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

# https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
[[dependencies.sekclib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
